# game.py
SCREEN_WIDTH, SCREEN_HEIGHT, TITLE = 640, 360, 'jester'
FONTSIZE = 24
FONTNAME = 'monaco'

# massage.py
LBUTTON = 4
RBUTTON = 5
PLAYERANGLE = 10 # depend this on game progress later
SPRITEWIDTH, SPRITEHEIGHT = 40, 90
PADDING = 20
PLAYERFINISHX = SCREEN_WIDTH * .8
MAXTIME = 10

# juggle.py
MINBALLX = SCREEN_WIDTH * .05
MAXBALLX = SCREEN_WIDTH * .5
